global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Airflow metrics (if available)
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    metrics_path: '/admin/metrics'
    scrape_interval: 30s

  # Neo4j metrics
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    scrape_interval: 30s

  # Dask scheduler metrics
  - job_name: 'dask-scheduler'
    static_configs:
      - targets: ['dask-scheduler:8787']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Kafka metrics (if JMX exporter is configured)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308'] # Assumes JMX exporter on port 9308
    scrape_interval: 30s

  # PostgreSQL metrics (if postgres_exporter is configured)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187'] # Assumes postgres_exporter on port 9187
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is configured)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121'] # Assumes redis_exporter on port 9121
    scrape_interval: 30s

  # Node/Container metrics (if node_exporter is available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Custom application metrics from Streamlit dashboard
  - job_name: 'orc-ai-dashboard'
    static_configs:
      - targets: ['streamlit-dashboard:8501']
    metrics_path: '/metrics'
    scrape_interval: 60s