global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "orc-ai-monitor"
    environment: "production"

rule_files:
  - "airflow_alerts.yml"
  - "recording_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Airflow Webserver metrics
  - job_name: "airflow-webserver"
    static_configs:
      - targets: ["airflow-webserver:8080"]
    scrape_interval: 30s
    metrics_path: /admin/metrics
    basic_auth:
      username: "${AIRFLOW_ADMIN_USERNAME}"
      password: "${AIRFLOW_ADMIN_PASSWORD}"

  # Redis metrics using Redis exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics using Postgres exporter
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Flower Celery monitoring
  - job_name: "flower"
    static_configs:
      - targets: ["airflow-flower:5555"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application metrics
  - job_name: "orc-ai-metrics"
    static_configs:
      - targets:
          [
            "airflow-webserver:8080",
            "airflow-scheduler:8080",
            "airflow-worker:8080",
          ]
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
# Enable remote write for long-term storage (optional)
# remote_write:
#   - url: "http://your-remote-storage:8086/api/v1/prom/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500
